# Generated by Django 4.2.4 on 2023-10-20 20:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartline",
            old_name="basket",
            new_name="cart",
        ),
    ]
