# Generated by Django 4.2.4 on 2023-10-27 17:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0002_rename_basket_cartline_cart"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartline",
            name="quantity",
        ),
    ]
