# Generated by Django 4.2.4 on 2023-10-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="token",
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                max_length=200, unique_for_date="publish", verbose_name="slug"
            ),
        ),
    ]
