# Generated by Django 4.2.4 on 2023-09-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_product_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="file",
            field=models.FileField(default=0, upload_to="files"),
            preserve_default=False,
        ),
    ]
