# Generated by Django 4.2.4 on 2023-10-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_productview_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productview",
            name="location",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
