# Generated by Django 4.2.4 on 2023-09-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_product_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="files"),
        ),
    ]
