# Generated by Django 4.2.4 on 2023-08-31 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_tag_product_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="bestseller",
            field=models.BooleanField(default=False, help_text="1=bestseller"),
        ),
        migrations.AddField(
            model_name="product",
            name="toprated",
            field=models.BooleanField(default=False, help_text="1=toprated"),
        ),
    ]
