# Generated by Django 4.2.4 on 2023-09-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_alter_product_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="category_products", to="products.tag"
            ),
        ),
    ]
